### ISSUE TITLE
The service "rms_push_notifications.android.gcm" has a dependency on a non-existent parameter

### ISSUE THREAD

**Issue by jperruchas** [richsage/RMSPushNotificationsBundle#126]
Hi,
I just updated the plugin today and I have this error : "The service "rms_push_notifications.android.gcm" has a dependency on a non-existent parameter "rms_push_notifications.android.dry_run". Did you mean one of these: "rms_push_notifications.android.class", "rms_push_notifications.android.enabled", "rms_push_notifications.android.c2dm.enabled", "rms_push_notifications.android.timeout", "rms_push_notifications.android.c2dm.username", "rms_push_notifications.android.c2dm.password", "rms_push_notifications.android.c2dm.source", "rms_push_notifications.android.gcm.enabled", "rms_push_notifications.android.gcm.api_key", "rms_push_notifications.android.gcm.dry_run", "rms_push_notifications.android.c2dm.class", "rms_push_notifications.android.gcm.class", "rms_push_notifications.ios.timeout"?
No issue yesterday... What's wrong ?

**Comment by richsage** [comment]
This is a change merged in this morning. There'll be a stable release out later today.

**Comment by richsage** [comment]
`master` should be fixed now however (incorrect parameter being passed), if you're tied to that.

**Comment by jperruchas** [comment]
Thank you?
I'm sorry to bore you but, when I'm trying to update my application with composer, I'm still have the error...
`pdating dependencies (including require-dev)
  - Updating richsage/rms-push-notifications-bundle dev-master (c19b7c4 => 2050caf)
    Checking out 2050cafd58fba8b3dbc67205f0fbf6c1cda128a1

Writing lock file
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
PHP Notice:  Undefined index: dry_run in /home/jerome/dev/www/appli/vendor/richsage/rms-push-notifications-bundle/RMS/PushNotificationsBundle/DependencyInjection/RMSPushNotificationsExtension.php on line 103
PHP Stack trace:
PHP   1. {main}() /home/jerome/dev/www/appli/app/console:0
PHP   2. Symfony\Component\Console\Application->run() /home/jerome/dev/www/appli/app/console:27
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /home/jerome/dev/www/appli/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:115
PHP   4. Symfony\Component\HttpKernel\Kernel->boot() /home/jerome/dev/www/appli/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:70
PHP   5. Symfony\Component\HttpKernel\Kernel->initializeContainer() /home/jerome/dev/www/appli/app/bootstrap.php.cache:2310
PHP   6. Symfony\Component\DependencyInjection\ContainerBuilder->compile() /home/jerome/dev/www/appli/app/bootstrap.php.cache:2531
PHP   7. Symfony\Component\DependencyInjection\Compiler\Compiler->compile() /home/jerome/dev/www/appli/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:576
PHP   8. Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process() /home/jerome/dev/www/appli/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php:108
PHP   9. Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process() /home/jerome/dev/www/appli/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/MergeExtensionConfigurationPass.php:39
PHP  10. RMS\PushNotificationsBundle\DependencyInjection\RMSPushNotificationsExtension->load() /home/jerome/dev/www/appli/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php:50
PHP  11. RMS\PushNotificationsBundle\DependencyInjection\RMSPushNotificationsExtension->setAndroidConfig() /home/jerome/dev/www/appli/vendor/richsage/rms-push-notifications-bundle/RMS/PushNotificationsBundle/DependencyInjection/RMSPushNotificationsExtension.php:42
`

**Comment by richsage** [comment]
Boo :-( OK - release 0.2.1 is out, this fixes that

**Comment by jperruchas** [comment]
All is good now !
Thank you  very much ! :-)
